name: alarm_tracker
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
